name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  cache: true

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      js_client: ${{ steps.changes.outputs.js_client }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: .github/file-filters.yml

  test_js:
    if: needs.changes.outputs.js_client == 'true'
    name: JS Client
    needs: changes
    uses: ./.github/workflows/test-js-client.yml
    secrets: inherit
